DROP TABLE IF EXISTS student;

CREATE TABLE student (
  id VARCHAR(250) AUTO_INCREMENT  PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  className VARCHAR(250) DEFAULT NULL,
  nationality VARCHAR(250) DEFAULT NULL
);
